spring:
  config:
    activate:
      on-profile: test

server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: WARN
    com.learning.eureka: INFO
